{% set name = "microfilm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microfilm-{{ version }}.tar.gz
  sha256: f06a458234a8bc5fec61eacf7523afbccde660e55b940deea58924a27a7b01ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - aicsimageio
    - h5py
    - imageio
    - imageio-ffmpeg
    - ipywidgets
    - matplotlib-base
    - matplotlib-scalebar
    - natsort
    - nd2reader
    - numpy
    - python >=3.7
    - scikit-image
    - tifffile
    - xarray

test:
  imports:
    - microfilm
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/guiwitz/microfilm
  summary: Creating figures and animations for multi-channel images with a focus on microscopy.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - guiwitz
